from mi_primer_app.models import Familiar
Familiar(nombre="Jeremías", apellido="Megías", direccion="Estados Unidos 1796", numero_dni=32239372).save()
Familiar(nombre="Laura", apellido="Megías", direccion="Estados Unidos 1796", numero_dni=31357669).save()
Familiar(nombre="Héctor Antonio", apellido="Megías", direccion="Estados Unidos 1796", numero_dni=11379789).save()
Familiar(nombre="Teresa", apellido="de Elías", direccion="Estados Unidos 1796", numero_dni=14476253).save()
print("Se cargo con éxito los usuarios de pruebas")